### ISSUE TITLE
ERROR while indexing siteroot: list index out of range

### ISSUE THREAD

**Issue by animus888** [collective/collective.elastic.ingest#14]
In Plone 6 there was a change with the site path structure (siteroot).
That's why we had to use following workaround:

/usr/local/lib/python3.11/site-packages/collective/elastic/ingest/ingest/section.py:15
`content["section"] = path.split("/")[1] if len(path.split("/"))>1 else "__root__"`

**Comment by ksuess** [comment]
Edge case fixed with https://github.com/collective/collective.elastic.ingest/pull/20
