### ISSUE TITLE
update mappings.json for plone6

### ISSUE THREAD

**Issue by animus888** [collective/collective.elastic.ingest#17]
![mappings_json](https://github.com/collective/collective.elastic.ingest/assets/86592335/bce6ef58-b1d0-4dc5-88a7-29d52c545bf5)
Tried mapping "blocks" and "blocks_layout" for plone6/volto as flattened fields (maybe not the ideal approach).

blocks_layout should be dropped via postprocessing -> not really necessary for indexing.

**Comment by ksuess** [comment]
See updated example of https://github.com/collective/collective.elastic.ingest/pull/19
